version: '3.8'

services:
  mysqldb:
    container_name: bookstore_db
    image: 'mysql:8.0.3'
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_DB=${APP_DB_DATABASE}
      - MYSQL_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_USER=${APP_DB_USER}
    ports:
      - ${APP_DB_DOCKER_PORT}:${APP_DB_LOCAL_PORT}
    volumes:
      - db-data:/var/lib/mysql/data
  bookstore_app:
    container_name: bookstore_api
    image: 'bookstore:latest'
    restart: on-failure
    env_file: ./.env
    ports:
      - ${APP_DOCKER_PORT}:${APP_LOCAL_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:mysql://mysqldb:$APP_DB_DOCKER_PORT/$APP_DB_DATABASE",
          "spring.datasource.username" : "${APP_DB_USER}",
          "spring.datasource.password" : "${APP_DB_PASSWORD}",
          "spring.jpa.properties.hibernate.dialect" : "${APP_DB_DIALECT}",
          "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    healthcheck:
      test: [ "CMD-SHELL", "mysql_isready -U mysql" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    depends_on:
      - mysqldb

volumes:
  db-data: